version: '3'
services:
  web:
    build: ./
    ports:
        - "5000:5000"
    environment:
    - DATABASE_URL=postgres://neondb_owner:npg_Aj9IicxVR6Og@ep-raspy-cake-a4er20z3.us-east-1.aws.neon.tech/neondb?sslmode=require
    depends_on:
        - db
  db:
    image: postgres:17.5
    environment:
        - POSTGRES_PASSWORD=npg_Aj9IicxVR6Og
        - POSTGRES_DB=myapp
    volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data:

    
