version: '3'
services:
  env_file:
      - prod.env
  web:
    build: ./
    ports:
        - "5000:5000"
    environment:
    - DATABASE_URL={$POSTGRES_URL_NON_POOLING}
    depends_on:
        - db
  db:
    image: postgres:17.5
    environment:
        - POSTGRES_PASSWORD=${PGPASSWORD}
        - POSTGRES_DB=myapp
    volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data:

    
